### ISSUE TITLE
TypeScript 7 runway: node10 moduleResolution is removed, not just deprecated

### ISSUE THREAD

**Issue by ajit-zer07** [agentcontextdistributionprotocol/acdp-control-plane#156]
Split out of #137. TypeScript 6 landed in #154; this issue tracks the runway to 7, because two options this repo currently depends on are **removed** (not merely deprecated) in TS 7.

## What breaks

`tsconfig.json` keeps `moduleResolution: "node"` (the legacy node10 algorithm) behind `ignoreDeprecations: "6.0"`. Measured against `typescript@7.0.2`, the repo's exact config produces one error:

```
tsconfig.json(21,25): error TS5108: Option 'moduleResolution=node10' has been removed.
```

`ignoreDeprecations` itself stops working in 7.0, so there is no second reprieve. `baseUrl` was the other deprecated option and was already deleted in #154 (it had no `paths` and nothing resolved through it).

## The migration is smaller than originally assumed

#137's plan rejected `nodenext` because it imposes ESM/CJS interop strictness on 100+ files, drizzle's exports map and the NAPI binding all at once. But TS 6.0 **newly permits** `module: "commonjs"` together with `moduleResolution: "bundler"` — that combination was `TS5095` under 5.9. `bundler` needs no `.js` import extensions, which makes it a materially smaller move than `nodenext`.

Both should be re-evaluated before adopting TS 7; the TODO in `tsconfig.json` records this inline.

## Also gated on this

`@typescript-eslint` currently peers `typescript <6.1.0`, and `.github/dependabot.yml` ignores `typescript` majors for that reason. Lifting that ignore is part of this work.

Refs #137, #154.

**Comment by ajit-zer07** [comment]
**Re-checked 2026-09-11 — TypeScript 7 is now GA, but this is blocked on the lint toolchain, not on the compiler.**

```
$ npm view typescript dist-tags
{ latest: '7.0.2', next: '7.1.0-dev.20260911.1', ... }

$ npm view @typescript-eslint/parser version peerDependencies
version: 8.70.0
peerDependencies: { "typescript": ">=4.8.4 <6.1.0", ... }
```

Worth stating explicitly, because the issue body above reads as though the remaining work is the `moduleResolution` migration: it isn't, yet. `typescript@7.0.2` is `latest`, but `@typescript-eslint/parser@8.70.0` — also `latest` — still caps `typescript` at `<6.1.0`. Installing TS 7 today makes `npm ci` fail with `ERESOLVE`, which is precisely the reason `.github/dependabot.yml:14-15` ignores `typescript` majors.

So the ordering is:

1. **Blocked:** wait for a `@typescript-eslint` release peering `typescript ^7`.
2. **Then** do the `moduleResolution` migration (`bundler` vs `nodenext`, per the analysis above) and drop `ignoreDeprecations`.
3. **Then** lift the dependabot ignore.

Step 2's analysis stands and is unaffected — `module: "commonjs"` + `moduleResolution: "bundler"` is still the smaller move. But it cannot land before step 1, so there is no actionable work here yet. Leaving open.
